/* Generated by automated build script */
#define SNAPSHOT
#define TEXTVER "Development snapshot 2016-01-26.0f1cab3"
#define SSHVER "PuTTY-Snapshot-2016-01-26.0f1cab3"
#define BINARY_VERSION 0,66,1080,0
