# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getPlayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='batted_ball',
            field=models.BooleanField(default=False, verbose_name='Batted Ball Map'),
        ),
        migrations.AddField(
            model_name='player',
            name='zone_map',
            field=models.BooleanField(default=False, verbose_name='Strike Zone Heat Map'),
        ),
        migrations.AlterField(
            model_name='player',
            name='data_year',
            field=models.IntegerField(default=False, verbose_name='Data from Year'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_text',
            field=models.CharField(max_length=200, verbose_name='Player Name'),
        ),
    ]
