# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 19:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getPlayer', '0003_auto_20160303_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_year_queried',
            field=models.PositiveSmallIntegerField(default=2016),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_queried',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 3, 14, 15, 6, 142563)),
        ),
        migrations.AlterField(
            model_name='year',
            name='year_value',
            field=models.PositiveSmallIntegerField(default=2016, verbose_name='Year'),
        ),
    ]
