# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_group', models.CharField(max_length=200)),
                ('position_held', models.CharField(blank=True, max_length=200, verbose_name='Position Held')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of Award')),
                ('reason', models.TextField(verbose_name='Reason for award')),
                ('date_awarded', models.DateField(verbose_name='Date Awarded')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerPos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('site', models.CharField(max_length=200, verbose_name='Location')),
                ('organization', models.CharField(max_length=200)),
                ('num_hours', models.IntegerField(verbose_name='Hours Worked')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(max_length=200, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
