# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160418_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='volunteerpos',
            options={'verbose_name': 'Volunteer Position', 'verbose_name_plural': 'Volunteer Positions'},
        ),
    ]
